import type { Metadata } from 'next'
import { Header } from '@/app/_components/header'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />

        <main>{children}</main>

        <footer>&copy; Copyright</footer>
      </body>
    </html>
  )
}
